require("catppuccin").setup({
  transparent_background = true,
  integrations = {
    mini = true,
    bufferline = true,
    mason = true,
    cmp = true,
    lsp_trouble = true,
    nvimtree = true,
    treesitter = true,
    symbols_outline = true,
    gitsigns = true,
    neogit = true,
    fidget = true,
  },
  color_overrides = {
    -- Carburetor
    mocha = {
      rosewater = "#ffd7d9",
      flamingo = "#ffb3b8",
      pink = "#ff7eb6",
      mauve = "#d4bbff",
      red = "#fa4d56",
      maroon = "#ff8389",
      peach = "#ff832b",
      yellow = "#fddc69",
      green = "#42be65",
      teal = "#3ddbd9",
      sky = "#82cfff",
      sapphire = "#78a9ff",
      blue = "#4589ff",
      lavender = "#be95ff",
      text = "#f4f4f4",
      subtext1 = "#e0e0e0",
      subtext0 = "#c6c6c6",
      overlay2 = "#a8a8a8",
      overlay1 = "#8d8d8d",
      overlay0 = "#6f6f6f",
      surface2 = "#525252",
      surface1 = "#393939",
      surface0 = "#262626",
      base = "#161616",
      mantle = "#0b0b0b",
      crust = "#000000"
    },
  },
  custom_highlights = function(colors)
    return {
      CmpItemMenu = { fg = colors.mauve, bg = "NONE", italic = true },
      CmpItemKindSnippet = { fg = colors.base, bg = colors.mauve },
      CmpItemKindKeyword = { fg = colors.base, bg = colors.red },
      CmpItemKindText = { fg = colors.base, bg = colors.teal },
      CmpItemKindMethod = { fg = colors.base, bg = colors.blue },
      CmpItemKindConstructor = { fg = colors.base, bg = colors.blue },
      CmpItemKindFunction = { fg = colors.base, bg = colors.blue },
      CmpItemKindFolder = { fg = colors.base, bg = colors.blue },
      CmpItemKindModule = { fg = colors.base, bg = colors.blue },
      CmpItemKindConstant = { fg = colors.base, bg = colors.peach },
      CmpItemKindField = { fg = colors.base, bg = colors.green },
      CmpItemKindProperty = { fg = colors.base, bg = colors.green },
      CmpItemKindEnum = { fg = colors.base, bg = colors.green },
      CmpItemKindUnit = { fg = colors.base, bg = colors.green },
      CmpItemKindClass = { fg = colors.base, bg = colors.yellow },
      CmpItemKindVariable = { fg = colors.base, bg = colors.flamingo },
      CmpItemKindFile = { fg = colors.base, bg = colors.blue },
      CmpItemKindInterface = { fg = colors.base, bg = colors.yellow },
      CmpItemKindColor = { fg = colors.base, bg = colors.red },
      CmpItemKindReference = { fg = colors.base, bg = colors.red },
      CmpItemKindEnumMember = { fg = colors.base, bg = colors.red },
      CmpItemKindStruct = { fg = colors.base, bg = colors.blue },
      CmpItemKindValue = { fg = colors.base, bg = colors.peach },
      CmpItemKindEvent = { fg = colors.base, bg = colors.blue },
      CmpItemKindOperator = { fg = colors.base, bg = colors.blue },
      CmpItemKindTypeParameter = { fg = colors.base, bg = colors.blue },
      CmpItemKindCopilot = { fg = colors.base, bg = colors.teal },
    }
  end
})
vim.cmd.colorscheme "catppuccin"
